alphas:
- 0.9
- 0.8
- 0.7
- 0.6
- 0.5
- 0.4
- 0.3
- 0.2
- 0.1
- 0.05
- 0.02
data_type: lane
pretrain_fraction: 0.5
methods:
- cpt
- cpt
- dtaci
- dtaci
- cpid
- cpid
- acmcp
- copulacp
- cfrnn
display_names:
- ACI
- ACI+
- DtACI
- DtACI+
- CPID
- CPID+
- ACMCP
- CopulaCPTS
- CFRNN
exp_ids:
- 41
- 40
- 41
- 40
- 41
- 40
- 41
- 41
- 41
config_ids:
- 41
- 40
- 41
- 40
- 41
- 40
- 41
- 41
- 41
