alphas:
- 0.9
- 0.8
- 0.7
- 0.6
- 0.5
- 0.4
- 0.3
- 0.2
- 0.1
- 0.05
- 0.02
data_type: hosp
methods:
- cpt
- cpt
- dtaci
- dtaci
- cpid
- cpid
- acmcp
- copulacp
- cfrnn
display_names:
- ACI
- ACI+
- DtACI
- DtACI+
- CPID
- CPID+
- ACMCP
- CopulaCPTS
- CFRNN
exp_ids:
- 61
- 60
- 61
- 60
- 61
- 60
- 61
- 61
- 61
config_ids:
- 61
- 60
- 61
- 60
- 61
- 60
- 61
- 61
- 61
