skip: {}

datas:
  - hosp
  - elec
  - weather

pretrain_fractions:
  - 0
  - 0
  - 0

config_ids:
  - 60
  - 70
  - 80

methods:
  - dtaci
  - cpt
  - cpid

batch_size: 8
iters: 500
output_id_base: 1000
output_id_step: 100
