# Best config for cyclone dataset
expand_boundaries_values:
  - -1
power: 0.3
B: 50
br_learning_rate: 0.4
var_a: 1
gamma: 0.1
score_window: 20
d_factor: 0.3
optim_arg:
  e_coeff: 0.01
  r_coeff: 0.1
optional_args:
  # Integer values
  ncal: 3

  # Boolean flags
  rolling: false
  scorecast: true
  integrate: true

  # Floating point values
  Csat: 1.0
  KI: 0.1
score_func_args:
  type: abs-r
  optional_args:
    quantile_d: 0.2
