window: 10
risk_type: absolute # absolute, relu
alphas:
  - 0.9
  - 0.8
  - 0.7
  - 0.6
  - 0.5
  - 0.4
  - 0.3
  - 0.2
  - 0.1
  - 0.05
  - 0.02

debug_alphas:
  - 0.9
  - 0.7
  - 0.5
  - 0.3
  - 0.1
  - 0.02