expand_boundaries_values:
  - 0
power: 0
B: 5
br_learning_rate: 0.4
var_a: 0.5
score_window: 20
gamma: 0.2
var_a: 1
d_factor: 1
max_delta: 0.15
optim_arg:
  mode: kernel
  knn_k: 20
  kernel_sigma: 1.8
  eps: 0.00000001
  max_additional_context: 1000
  
  # context settings
  traj_type: scores
  data_options:
    scores:
      use: false
      context_size: 8
      context_option: line
    ground_truth:
      use: false
    betas:
      use: false
    preds:
      use: true
      context_size: 8

  # optimization args
  e_coeff: 1000
  r_coeff: 0.5

score_func_args:
  type: abs-r
  optional_args:
    quantile_d: 0.2
